---
title: About this site
author: Patrick D. Elliott
date: 21.10.2018
---

* About this site

** Publishing

- This is a static site built using [[https://jaspervdj.be/hakyll/][hakyll]], and hosted via [[https://pages.github.com/][GitHub pages]].
- I support the movement to /decentralize the web/; as such, you can also access
  this site via modern peer-to-peer protocols.
 - You can find me via [[https://datproject.org/][dat]] @ [[dat://patrl.hashbase.io]], using, e.g., [[https://beakerbrowser.com/][beaker browser]].
 - You can find me on the [[https://ipfs.io/][IPFS]] network at ~ipns/patrickdelliott.com~. If you use
   the [[https://github.com/ipfs-shipyard/ipfs-companion][IPFS companion]] browser extension, then you should be automatically redirected.

** Design

- This site is built to be fast and responsive using a custom theme built with
  the [[http://tachyons.io/][tachyons]] css framework - it is 100% javascript free.
  The theme is tailored to style html generated by ~pandoc~.
- The font is bold monday's beautiful [[https://www.boldmonday.com/news/new-work-meet-ibm-plex/][IBM Plex]] typeface.

** Content

- The vast majority of the content is written in [[https://orgmode.org/][emacs org-mode]], and converted
  to html5 via pandoc's built-in ~org-mode~ reader.

** Need my help?

- In my spare time, I design sites using cutting-edge web technologies. If you'd
  like to work with me on a website get in touch @ [[mailto:patrick.d.elliott@gmail.com][patrick.d.elliott(at)gmail.com]].
