---
title: Conceptual Mathematics
author: Patrick D. Elliott
date: 19.10.2018
reference-section-title: References
---

#+latex_compiler: xelatex
#+latex_header: \usepackage{libertine}
#+latex_header: \usepackage{unicode-math}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{braket}

* Exercises
:PROPERTIES:
:NOTER_DOCUMENT: ../../gdrive/library/lawvere2009.pdf
:END:

** Isomorphisms exercise 1 (p58)
:PROPERTIES:
:NOTER_PAGE: 58
:END:

*** Prove that \(1_A\) is an isomorphism.

There is an inverse of \(1_A\) - namely, \(1_A\), since:
  - \(1_A \circ 1_A = 1_A\), by the *Identity Laws*.
  - Since \(1_A\) has an inverse, \(1_A\) is an isomorphism.

*** Show that if \(A \xrightarrow{f} B\) is an isomorphism, and \(B \xrightarrow{g} A\) is an inverse for \(f\), then \(g\) is also an isomorphism

If \(B \xrightarrow{g} A\) is an inverse for \(A \xrightarrow{f} B\), then
  the following must hold:

  $$g \circ f = 1_A$$

  $$f \circ g = 1_B$$

Since these two properties must hold, \(f\) must be an inverse for \(g\). Since \(g\) has an inverse, \(g\) must be an isomorphism.

*** Prove that if \(A \xrightarrow{f} B\) and \(B \xrightarrow{k} C\) are isomorphisms, \(A \xrightarrow{k \circ f} C\) is also an isomorphism.

If \(f\) and \(k\) are isomorphisms, they must have inverses \(B
  \xrightarrow{g} A\) and \(C \xrightarrow{l} B\) with the following properties:

  \[g \circ f = 1_A\]

  \[f \circ g = 1_B\]

  \[l \circ k = 1_B\]

  \[k \circ l = 1_C\]

  If \(k \circ f\) is an isomorphism, it should have an inverse \(h\), with the
  following properties:

  \[h \circ k \circ f = 1_A\]

  \[k \circ f \circ h = 1_C\]

  A map with such a property is the composition of the inverses of \(f\) and
  \(k\), namely \(g \circ l\), since:

  \[g \circ l \circ k \circ f\]

  1. \(g \circ (l \circ k) \circ f\) (by associativity)
  2. \(= g \circ 1_B \circ f\) (by substitution)
  3. \(= g \circ (1_B \circ f)\) (by associativity)
  4. \(= g \circ f\) (by the identity laws)
  5. \(= 1_A\) (by subsitution)

  Therefore: \(g \circ l \circ k \circ f = 1_A\)

  \[k \circ f \circ g \circ l\]

  1. \(= k \circ (f \circ g) \circ l\) (by associativity)
  2. \(= k \circ 1_B \circ l\) (by subsitution)
  3. \(= k \circ (1_B \circ l)\) (by associativity)
  4. \(= k \circ l\) (by the identity laws)
  5. \(= 1_C\) (by substitution)

  Therefore: \(k \circ f \circ g \circ l = 1_C\)
