---
title: About
author: Patrick D. Elliott
lang: English
date: 18.11.2018
---

I'm a postdoctoral researcher at the [[https://www.zas.gwz-berlin.de][Leibniz-Zentrum Allgemeine
Sprachwissenschaft]] in Berlin, associated with the semantics and pragmatics
research group. I'm a theoretical linguist, which means that my work involves
developing formal models of what we know when we know a language. Mostly, I do
semantics, but I'm also interested in syntax, morphology, pragmatics, and their interfaces with semantics.

When I'm not doing linguistics, I [[https://github.com/patrl][code]], [[https://www.goodreads.com/user/show/59694544-patrick-elliott][read]], and scale vertical walls.

Reach me at: [[mailto:patrick.d.elliott@gmail.com][patrick.d.elliott(at)gmail.com]]

*** Upcoming

- December 14.12, 2018: I'll be giving a guest seminar at the [[http://danielrothschild.com/attitudes/][UCL semantics of
  attitudes]] series entitled "Arguments and Attitudes".
- March 6-8, 2019: I'll be giving an invited talk at the DGfS workshop [[https://sites.google.com/site/encodingemotiveattitudes/][Emo 2019]]
  in Bremen entitled "The Dynamics of Expressive Content".
- I have two papers in preparation for the /Proceedings of LENLS
  15/, one with Yasu Sudo entitled "Binding /Ex Post Facto/", and one by myself
  entitled "Applicatives for Anaphora and Presupposition".
- I have a paper in preparation for the /Proceedings of Sinn und Bedeutung 23/
  with Uli Sauerland entitled "Ineffability and unexhaustification".
