---
title: About
author: Patrick D. Elliott
lang: English
date: 03.13.2020
---

I'm a visiting faculty member in the linguistics & philosophy department at MIT.
I'm a theoretical linguist, which means that my work involves developing formal models of what we know when we know a language. Mostly, I do semantics, but I'm also interested in syntax, morphology, pragmatics, and their interfaces with semantics.

When I'm not doing linguistics, I [[https://github.com/patrl][code]], [[https://www.goodreads.com/user/show/59694544-patrick-elliott][read]], and scale vertical walls. Reach me
at ~pdell@mit.edu~, or via [[https://keybase.io/patrl/chat][encrypted chat]].

*** Recent and upcoming

- July 2020: I have a new ms. (in prep) entitled /Coreference, negation, and modal subordination/. Contact me directly for a draft.
- July 2020: I have a new ms. on lingbuzz entitled /Exceptional de re in continuation semantics/, which can be found [[https://ling.auf.net/lingbuzz/005297][here]].
- June 2020: I have a new ms. on lingbuzz entitled /Crossover and accessibility in dynamic semantics/, which can be found [[https://ling.auf.net/lingbuzz/005311][here]].
- March 2020: I have a new manuscript entitled /A flexible scope theory of
  intensionality/, which can be found [[https://ling.auf.net/lingbuzz/005107][here]].
- January 2020: I uploaded a corrected version of my PhD dissertation /Elements
  of Clausal Embedding/ to semantics archive and lingbuzz. It can be downloaded
  from [[https://semanticsarchive.net/Archive/2YyN2M5N/][here]].
- Spring semester 2020: I taught a semantics seminar at MIT with Martin Hackl,
  entitled /Getting high: scope, projection, and evaluation order/. The class
  web page can be found [[http://stellar.mit.edu/S/course/24/sp20/24.979/][here]].
- August, 2020: I'm giving a talk at SALT with Yasu Sudo, entitled /Generalized
  crossover/.
