---
title: About
author: Patrick D. Elliott
lang: English
date: 18.11.2018
---

I'm a postdoctoral researcher at the [[https://www.zas.gwz-berlin.de][Leibniz-Zentrum Allgemeine
Sprachwissenschaft]] in Berlin, associated with the semantics and pragmatics
research group. I'm a theoretical linguist, which means that my work involves
developing formal models of what we know when we know a language. Mostly, I do
semantics, but I'm also interested in syntax, morphology, pragmatics, and their interfaces with semantics.

When I'm not doing linguistics, I [[https://github.com/patrl][code]], [[https://www.goodreads.com/user/show/59694544-patrick-elliott][read]], and scale vertical walls.

Reach me at: [[mailto:patrick.d.elliott@gmail.com][patrick.d.elliott(at)gmail.com]]

*** Upcoming

- April 12-13, 2019: I'll be giving a joint talk with Yasu Sudo at [[https://voices.uchicago.edu/sluicingat50/][SLUICING+@50]]
  in Chicago entitled "The dynamics of ellipsis identity".
- June 11, 2019: I'll be giving an invited talk at Göttingen university entitled
  "The two souls of disjunction".
- July 1-3, 2019: I'll be giving two talks at the workshop /Asymmetries in
  language: presuppositions and beyond/ at ZAS Berlin. One by myself entitled
  "Two souls of disjunction: towards a state-monadic update semantics", and one
  joint with Yasu Sudo entitled "Binding back from the future".
- I have a paper to appear in the /Proceedings of LENLS 15/ entitled "Applicatives for Anaphora and Presupposition".
- I have a paper to appear in the /Proceedings of Sinn und Bedeutung 23/
  with Uli Sauerland entitled "Ineffability and unexhaustification".
