---
title: About
author: Patrick D. Elliott
lang: English
date: 22.08.2019
---

I'm a postdoctoral associate in the linguistics & philosophy department at MIT.
I'm a theoretical linguist, which means that my work involves developing formal
models of what we know when we know a language. Mostly, I do semantics, but I'm also interested in syntax, morphology, pragmatics, and their interfaces with semantics.

When I'm not doing linguistics, I [[https://github.com/patrl][code]], [[https://www.goodreads.com/user/show/59694544-patrick-elliott][read]], and scale vertical walls.

Reach me at: ~pdell@mit.edu~

*** Upcoming

- June 11, 2019: I gave an invited talk at Göttingen university entitled
  "Movement as higher-order structure building". [[https://patrl.keybase.pub/slides/goettingen-mvt.pdf][slides]]
- June 13-14, 2019: I gave a joint talk with Uli Sauerland at the
  workshop [[https://www.xprag.de/?page_id=6207][Exhaustivity in Questions and Answers]] entitled "Nuclear intervention:
  deriving Beck effects via cyclic scope and local exhaustification", in
  Tübingen. [[https:://patrl.keybase.pub/slides/tuebingen-slides.pdf][slides]]
- July 1-3, 2019: I gave two talks at the workshop /Asymmetries in
  language: presuppositions and beyond/ at ZAS Berlin. One by myself entitled
  "Two souls of disjunction: towards a state-monadic update semantics" ([[https://patrl.keybase.pub/slides/berlin-disj.pdf][slides]]), and one
  joint with Yasu Sudo entitled "Binding back from the future" ([[https://patrl.keybase.pub/slides/berlin-cataphora.pdf][slides]]).
- I have a paper to appear in the /Proceedings of LENLS 15/ entitled "Applicatives for Anaphora and Presupposition".
- I have a paper to appear in the /Proceedings of Sinn und Bedeutung 23/
  with Uli Sauerland entitled "Ineffability and unexhaustification".
