---
title: About
author: Patrick D. Elliott
lang: English
date: 20.02.2021
---

I'm currently [[https://linguistics.mit.edu/user/pdell/][a visiting faculty member in the linguistics & philosophy department at MIT]].

I'm a theoretical linguist, which means that my work involves developing formal models of what we know when we know a language. Mostly, I work on semantics and pragmatics; I'm also interested in computational approaches to meaning and the syntax-semantics interface.

When I'm not doing linguistics, I [[https://github.com/patrl][code]], run, and scale vertical walls. Reach me at ~pdell(at)mit.edu~.

*** Recent and upcoming

- December 8, 2020: I gave a talk at MIT CompLang entitled /What linguists can learn from functional programmers: A study in opacity and environment sensitivity/.
- November 2020: I have a new ms. on lingbuzz entitled /Towards a principled logic of anaphora/, which can be found [[https://ling.auf.net/lingbuzz/005562][here]].
- November, 2020: I gave an invited talk at [[http://www.is.ocha.ac.jp/~bekki/lenls/][/Logic and Engineering of Natural Language Semantics 17/]], entitled /Classical negation in a dynamic alternative semantics/. [[https://patrl.keybase.pub/slides/lenls2020.pdf][Slides]].
- October 27, 2020: I gave a talk at the Rutgers SURGE meeting, entitled /Coreference, negation, and modal subordination/.
- October 9, 2020: I gave a talk at the NYU semantics group, entitled /Crossover and the dynamics of negation/.
- September, 2020: I have a commentary in a special issue of /Theoretical Linguistics/, entitled /A plea for equality: remarks on Moltmann's semantics for clausal embedding/, which can be found [[https://ling.auf.net/lingbuzz/005440][here]].
- July 2020: I have a new ms. (in prep) entitled /Coreference, negation, and modal subordination/. Contact me directly for a draft.
